<?php
namespace ItbTests;

use Silex\WebTestCase;

use Itb\UserController;
use Symfony\Component\HttpFoundation\Request;


class UserControllertTest extends WebTestCase
{
    private $request;

    public function createApplication()
    {
        // app.php must return an Application instance
        $app = require __DIR__ . '/../app/setup.php';
        unset($app['exception_handler']);

        // allows us to test sessions
        $app['session.test'] = true;

        return $app;
    }

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->request = new Request(['', 'get']);
    }

    public function testGetLogin()
    {
        // Arrange
        $expectedText = 'login';
        $mainController = new UserController();

        // Act
        $result = $mainController->loginAction($this->request, $this->app);

        // Assert
        $this->assertContains($expectedText, $result);
    }

    public function testPostLogin()
    {
        // Arrange
        $expectedText = 'success';
        $mainController = new UserController();

        // create a POST method Request object
        // to simulate form data being submitted (which we can test behaviour against)
        $postRequest = new Request(['', 'post']);

        // set POST values in request - simulating data from form
        $postRequest->request->set('username', 'matt');
        $postRequest->request->set('password', 'smith');


        // Act
        $result = $mainController->loginCheckAction($postRequest, $this->app);

        // Assert
        $this->assertContains($expectedText, $result);
    }




}